### PR TITLE
Fix #3

### LINKED ISSUE #3: <sw-update-toast> causes an error when SW is install for the first time
I've added `<sw-update-toast>` to my web app. When I opens the app in the browser for the first time, I get the following error in the browser console:

```
sw-update-toast.html:63 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined
    at navigator.serviceWorker.getRegistration.then (sw-update-toast.html:63)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@morbidick Please merge this pull request. :wink:

**Comment by morbidick** [comment]
don't we still need to check for undefined? At least according to  https://developer.mozilla.org/de/docs/Web/API/ServiceWorkerContainer/getRegistration the promise can return undefined.

Everything else looks good.

**Comment by FluorescentHallucinogen** [comment]
@morbidick Good catch! The promise will be resolved to `undefined`, if e.g. the web app has no service workers at all. Fixed. ;)

BTW, what if the app has more than one service workers?

**Comment by morbidick** [comment]
@FluorescentHallucinogen looks good, thx for your work! im going to merge this. 

For multiple ServiceWorkers there is the getRegistration**s** [1] call which is marked as even more experimental. We could feature detect it and register on the returned array. Im not sure if there is a use case yet? Im open for more PRs ;)

[1] https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/getRegistrations

**Pull request merged**
